SHREK Job Submission 2022-08-12 14:29:11.188404
cmd args: 
Namespace(yaml=['workflows/HF_pp200_charm-ana.315/runPileup.yaml', 'workflows/HF_pp200_charm-ana.315/runCalorimeter.yaml', 'workflows/HF_pp200_charm-ana.315/runPass3Track.yaml', 'workflows/HF_pp200_charm-ana.315/runPass4TrackStage0.yaml', 'workflows/HF_pp200_charm-ana.315/runPass4TrackStageA.yaml', 'workflows/HF_pp200_charm-ana.315/runPass4TrackStageC.yaml', 'workflows/HF_pp200_charm-ana.315/mergeOutputs.yaml'], tag='sP22r-hfcharm-pileup-test5-newwf', offset=200000, submit=True, check=True, handshake=True, uuid=False, vo='wlcg', site='BNL_OSG_SPHENIX', prodSourceLabel='test', workingGroup='sphenix', user='jwebb2', branch='test')
subdir: 
/direct/sphenix+u/jwebb2/work/2022/SHREK/sPHENIX-test-production/sP22r-hfcharm-pileup-test5-newwf
tag: 
sP22r-hfcharm-pileup-test5-newwf
check:
b'INFO : uploading workflow sandbox\nINFO : check workflow user.jwebb2.sP22r-hfcharm-pileup-test5-newwf\nINFO : messages from the server\n2022-08-12 18:29:10.107467 : start /var/cache/pandaserver/workflow.3a0c6954-38c6-41b4-af3b-24f6f926b1e6\n2022-08-12 18:29:10.650004 : downloading sandbox from https://pandaserver-doma.cern.ch:25443/cache/jobO.d5ea794a-d4cc-43f8-be7f-56e6cffbe82f.tar.gz\n2022-08-12 18:29:10.693212 : parse workflow\n2022-08-12 18:29:11.027386 : failed to run with while constructing a mapping\n  in "<unicode string>", line 17, column 5:\n        type: string\n        ^ (line: 17)\nfound duplicate key "outputSource" with value "Pythia8Pass4TrackStageC/outDS" (original value: "Pythia8CharmOutput/outDS")\n  in "<unicode string>", line 19, column 5:\n        outputSource: Pythia8Pass4TrackS ... \n        ^ (line: 19)\n\nTo suppress this check see:\n    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\n\nDuplicate keys will become an error in future releases, and are errors\nby default when using the new API.\n Traceback (most recent call last):\n  File "/opt/panda/lib64/python3.6/site-packages/pandaserver/taskbuffer/workflow_processor.py", line 169, in core_exec\n    tmpLog)\n  File "/opt/panda/lib64/python3.6/site-packages/pandaserver/workflow/pcwl_utils.py", line 56, in parse_workflow_file\n    root_obj = load_document_by_uri(cwl_file)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/__init__.py", line 80, in load_document_by_uri\n    return load_document_by_string(doc, baseuri, loadingOptions)\n  File "/opt/panda/lib64/python3.6/site-packages/cwl_utils/parser/__init__.py", line 101, in load_document_by_string\n    result = yaml.load(string)\n  File "/opt/panda/lib64/python3.6/site-packages/ruamel/yaml/main.py", line 343, in load\n    return constructor.get_single_data()\n  File "/opt/panda/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 113, in get_single_data\n    return self.construct_document(node)\n  File "/opt/panda/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 123, in construct_document\n    for _dummy in generator:\n  File "/opt/panda/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 1563, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File "/opt/panda/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 1469, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File "/opt/panda/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 146, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File "/opt/panda/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object\n    for _dummy in generator:\n  File "/opt/panda/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 1563, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File "/opt/panda/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 1469, in construct_mapping\n    value = self.construct_object(value_node, deep=deep)\n  File "/opt/panda/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 146, in construct_object\n    data = self.construct_non_recursive_object(node)\n  File "/opt/panda/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 188, in construct_non_recursive_object\n    for _dummy in generator:\n  File "/opt/panda/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 1563, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File "/opt/panda/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 1470, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n  File "/opt/panda/lib64/python3.6/site-packages/ruamel/yaml/constructor.py", line 295, in check_mapping_key\n    raise DuplicateKeyError(*args)\nruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping\n  in "<unicode string>", line 17, column 5:\n        type: string\n        ^ (line: 17)\nfound duplicate key "outputSource" with value "Pythia8Pass4TrackStageC/outDS" (original value: "Pythia8CharmOutput/outDS")\n  in "<unicode string>", line 19, column 5:\n        outputSource: Pythia8Pass4TrackS ... \n        ^ (line: 19)\n\nTo suppress this check see:\n    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\n\nDuplicate keys will become an error in future releases, and are errors\nby default when using the new API.\n\n\n\nERROR : workflow description is corrupted\n'
b''
submit:
2022-08-12 18:29:15.399697
b'INFO : uploading workflow sandbox\nINFO : gathering files under /direct/sphenix+u/jwebb2/work/2022/SHREK/sPHENIX-test-production/sP22r-hfcharm-pileup-test5-newwf\nINFO : upload source files\nINFO : submit workflow user.jwebb2.sP22r-hfcharm-pileup-test5-newwf\nINFO : request was accepted and will be processed in a few minutes\n'
b''